    openapi: 3.0.3
    info:
      version: 0.0.1
      title: API to Powershell Universal IT services portal - by Microb.vn
      description: |-
        A Set of API's to communicate with the Powershell Universal IT services portal.
        It provides access to tables to fill statistics graphs published by the portal
        and endpoint to retrieve and update outstanding requests made by the portal /users
    servers:
      - url: http://192.168.123.200:5000/cli/api
        description: Our current test server
    paths:
      /request/{type}:
        get:
          summary: Returns request(s) based on query type .
          parameters:
          - name: type
            in: path
            required: true
            description: |-
              Either the value 'open', 'process' or an integer value.<br>
              - 'open' will return all open requests with a maximum of 15 per call.<br>
              - 'process' will return all requestsID's (only) of open requests with a maximum of 15 per call, and set the status of these requests into 'InProgess'.<br>
              - any numeric value will return the entry where cliRequestID matches the entered number.<br>
              
            schema:
              type : string
          responses:
            '200':
              description: Zero or more open request objects.  Please note that when type is 'process', only the cliRequestId attribute is returned!
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      cliRequestId:
                        description: Unique sequence number.
                        type: integer
                        format: int64
                        example: 4
                      cliTenantCode:
                        description: clientcode the request was made for
                        type: string
                        example: cli
                      cliRequestType:
                        description: Code for the request type
                        type: string
                        example: R-MAD-001
                      cliRequestor:
                        description: UserID of requestor
                        type: string
                        example: User@cuckoomail.org
                      cliPayload:
                        description: Request specific JSON request payload
                        type: string
                        example: "{\"resourcename\":\"HPAIO\",\"allowaccess\":\"rob,guda\",\"removeaccess\":\"nobody\"}"
                      cliStatus:
                        description: |-
                          Request processing status. can be Open, InProgress, Failed, Closed
                        type: string
                        example: Open
                      cliNotes:
                        description: "Processing notes/feedback for enduser"
                        type: string
                        example: "2024-03-23 18:00:01 Submitted"
            '400':
              description: "Bad request. (with optional error details)"
        put:
          summary: Updates a request based on body payload content .
          parameters:
          - name: Type
            in: path
            required: true
            description: |-
              The numeric value of the request entry to update
            schema:
              type : integer
          requestBody:
            description: Update Payload
            required: true
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - updatePayload
                  properties:
                    cliRequestor:
                      type: string
                      description: Required! Must be same as requestor in entry to update
                    cliTenantCode:
                      type: string
                      description: Required! Must be same as TenantCode in entry to update
                    cliStatus:
                      type: string
                      description: Optional new statuscode. Acceptable values are Open, Closed, ClosedIncomplete and Failed
                    cliNotes:
                      type: string
                      description: Optional set of notes. Can include Cr/Lf characters

          responses:
            '200':
              description: Processing done, Ok
            '400':
              description: "Bad request. (with optional error details)"
